name: Ubuntu
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: idris build and test
        run: |
          make clean && make build && make install && make test
        shell: bash
